### PR TITLE
fix: improve type compatibility with eslint

### LINKED ISSUE #225: `RuleListener` type is incompatible with ESLint's `RuleVisitor`
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [ ] I'm using [eslint-plugin-jsonc](https://github.com/ota-meshi/eslint-plugin-jsonc). (`*.json` file linting does not work with the parser alone. You should also use eslint-plugin-jsonc with it.)
- [x] I'm sure the problem is a parser problem. (If you are not sure, search for the issue in [eslint-plugin-jsonc](https://github.com/ota-meshi/eslint-plugin-jsonc) repo and open the issue in [eslint-plugin-jsonc](https://github.com/ota-meshi/eslint-plugin-jsonc) repo if there is no solution.
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.

### What version of ESLint are you using?

9.34.0

### What version of `eslint-plugin-jsonc` and ` jsonc-eslint-parser` are you using?

- jsonc-eslint-parser@2.4.0

### What did you do?

Coming from https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/issues/1242#issuecomment-3246235765, we're using the types from `jsonc-eslint-parser` as part of the types for our `eslint-plugin-package-json` (which uses the parser in its configs), and users have reported that when shifting from TSEslint's `config` function to ESLint's built-in `defineConfig` function for creating a config, the type of our plugin is incompatible.  I've traced it down to an incompatibility with the `RuleListener` exported from this package, and the `NodeListener` / `RuleVisitor` that `ESLint` expects as the return type for a `create` function. 

Tangentially, I think you'll have a similar issue with the `eslint-plugin-jsonc` package, as it's setting the types up in a similar way: https://github.com/ota-meshi/eslint-plugin-jsonc/blob/master/lib/types.ts#L34

### What did you expect to happen?

I found that if we swap in eslint's `NodeListener`, in place of `RuleListener`, it resolved the type issue on our side, but we lost some of the type inference that this package's type provided.  So, we were thinking it might be more appropriate to address the issue here, rather than working around it downstream.

### What actually happened?

This is an example of the type error

```
Type '{ configs: { "legacy-recommended": { plugins: string[]; rules: { "package-json/valid-package-definition": ["error", { ignoreProperties: string[]; }]; }; }; recommended: { files: string[]; languageOptions: { ...; }; name: string; plugins: { ...; }; rules: { ...; }; }; }; meta: { ...; }; rules: Record<...>; }' is not assignable to type 'Plugin'.
  Types of property 'rules' are incompatible.
    Type 'Record<string, PackageJsonRuleModule<unknown[]>>' is not assignable to type 'Record<string, RuleDefinition<RuleDefinitionTypeOptions>>'.
      'string' index signatures are incompatible.
        Type 'PackageJsonRuleModule<unknown[]>' is not assignable to type 'RuleDefinition<RuleDefinitionTypeOptions>'.
          The types returned by 'create(...)' are incompatible between these types.
            Type 'RuleListener' is not assignable to type 'RuleVisitor'.
              'string' index signatures are incompatible.
                Type 'RuleFunction<never> | undefined' is not assignable to type '((...args: any[]) => void) | undefined'.
                  Type 'RuleFunction<never>' is not assignable to type '(...args: any[]) => void'.
                    Types of parameters 'node' and 'args' are incompatible.
                      Type 'any' is not assignable to type 'never'.ts(2322)
```

### Link to **GitHub Repo** with Minimal Reproducible Example

https://github.com/JoshuaKGoldberg/eslint-plugin-package-json

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by michaelfaith**
This change adjusts the `RuleFunction` generic type to default to `any` for the Node, instead of `never`.

Fixes #225

### CODE REVIEW

File: src/types.ts [hunk 1]
```diff
@@ -6,7 +6,8 @@ export interface JSONParserOptions {
   jsonSyntax?: JSONSyntax;
 }
 
-export type RuleFunction<Node extends AST.JSONNode = never> = (
+// eslint-disable-next-line @typescript-eslint/no-explicit-any -- used for compatibility with ESLint types
+export type RuleFunction<Node extends AST.JSONNode = any> = (
```
Comment (JoshuaKGoldberg) [inline src/types.ts:10]: Thinking: would it be good to add a types test to verify this works?

Comment (michaelfaith) [reply src/types.ts:10]: Ok, update.  I had a good setup, started, and then realized this repo only has eslint v8 installed, which doesn't even have the latest types to test with 😭.  I don't think updating all of the infra in the repo to test this properly is really in scope of the PR. 

For what it's worth, this is what I had set up for type checking as part of `npm test`

```ts
import type { ESLint, Rule } from "eslint";
import type { RuleListener } from "../../src/types";

interface RuleContext<Options extends unknown[] = unknown[]>
	extends Rule.RuleContext {
	options: Options;
}

interface RuleModule<RuleOptions extends unknown[] = unknown[]> {
  create(context: RuleContext<RuleOptions>): RuleListener;
  meta: Rule.RuleMetaData;
}

const rule = {
  meta: {
    type: "suggestion",
  },
  create() {
    return {
      JSONProperty(node) {
        console.assert(node.type === "JSONProperty", "should be JSONProperty");
      },
    };
  },
} satisfies RuleModule;

const rules = {
  // eslint-disable-next-line @typescript-eslint/naming-convention -- test
  "test-rule": rule,
};

const plugin = {
  rules,
} satisfies ESLint.Plugin;

// This is just so the plugin variable is used.
console.assert(plugin.rules["test-rule"] === rule, "should be same");
```

Which, effectively, models a real world plugin use case.

Comment (michaelfaith) [reply src/types.ts:10]: Even then, that feels a bit too far for the scope of this change, but open to exploring it, if you want.

Comment (michaelfaith) [reply src/types.ts:10]: @ota-meshi any preference on this?

**Review by ota-meshi — APPROVED** [review]
Thank you!
